name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3 # Increase the timeout to 30 minutes
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
      # Steps remain the same
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests responses

      - name: Run tests
        run: |
          python -m unittest discover tests
