name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1 # Increase the timeout to 30 minutes
    strategy:
      matrix:
        python-version: [3.9] # Only test against Python 3.9
    steps:
      # Steps remain the same
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app
        run: nohup python app.py &

      - name: Run tests
        run: |
          python -m unittest discover tests
